# Generated by Django 4.2.16 on 2024-10-11 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_watchlist_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="watchlist",
            name="user",
        ),
    ]
