name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    # Step 1: Checkout the code
    - uses: actions/checkout@v4

    # Step 2: Set up Python with the specified version
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    # Step 3: Cache pip dependencies to speed up builds
    - name: Cache pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    # Step 4: Install dependencies
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 5: Run database migrations (optional)
    - name: Run Migrations (if applicable)
      working-directory: SEENEMA_API
      run: |
        python manage.py migrate

    # Step 6: Run tests
    - name: Run Tests
      working-directory: SEENEMA_API
      run: |
        python manage.py test
